export type UserRole = 'ADMIN' | 'ATENDENTE';

export interface UserProfile {
  id: string;
  authUserId: string;
  name: string;
  email: string;
  role: UserRole;
  active: boolean;
  attendantId?: string; // Presente caso seja ATENDENTE vinculado a um atendente específico
  createdAt: string;
  updatedAt: string;
  lastLoginAt?: string;
}

export interface Attendant {
  id: string;
  name: string;
  code: string;
  active: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface TreatmentSupport {
  id: string;
  date: string; // Formato YYYY-MM-DD
  attendantId: string;
  quantity: number;
  observation?: string;
  createdBy: string;
  updatedBy?: string;
  createdAt: string;
  updatedAt: string;
  deletedAt?: string | null;
  deletedBy?: string | null;
  version: number;
}

export type SupportAuditAction = 'CREATE' | 'UPDATE' | 'DELETE' | 'RESTORE';

export interface TreatmentSupportAudit {
  id: string;
  treatmentSupportId: string;
  userId: string;
  userName: string;
  action: SupportAuditAction;
  oldValue: Partial<TreatmentSupport> | null;
  newValue: Partial<TreatmentSupport> | null;
  createdAt: string;
}

export type AuditLogAction =
  | 'LOGIN'
  | 'LOGOUT'
  | 'LOGIN_FAILED'
  | 'USER_CREATED'
  | 'USER_UPDATED'
  | 'USER_DISABLED'
  | 'PASSWORD_RESET'
  | 'SUPPORT_CREATED'
  | 'SUPPORT_UPDATED'
  | 'SUPPORT_DELETED'
  | 'SUPPORT_RESTORED'
  | 'GOAL_CREATED'
  | 'GOAL_UPDATED'
  | 'AI_CONFIG_UPDATED'
  | 'AI_API_KEY_UPDATED'
  | 'AI_API_KEY_REMOVED'
  | 'AI_CONNECTION_TESTED'
  | 'AI_CONNECTION_FAILED';

export interface AuditLog {
  id: string;
  userId: string;
  userName: string;
  userRole: UserRole;
  action: AuditLogAction;
  entityType: string;
  entityId?: string;
  metadata?: Record<string, unknown>;
  createdAt: string;
  ipAddress?: string;
}

export type GoalType = 'DAILY_STORE' | 'MONTHLY_STORE' | 'DAILY_ATTENDANT' | 'MONTHLY_ATTENDANT';

export interface Goal {
  id: string;
  type: GoalType;
  attendantId?: string;
  targetValue: number;
  startDate: string; // YYYY-MM-DD
  endDate?: string | null; // YYYY-MM-DD
  active: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface AISettings {
  id: string;
  provider: 'Google Gemini';
  model: string; // padrão: 'gemini-3.6-flash'
  enabled: boolean;
  isKeyConfigured: boolean; // Flag booleana - A chave NUNCA é enviada ao frontend
  dailyAnalysisEnabled: boolean;
  monthlyAnalysisEnabled: boolean;
  autoGenerateDaily: boolean;
  autoGenerateMonthly: boolean;
  createdAt: string;
  updatedAt: string;
  updatedBy: string;
}

export type AIAnalysisType = 'DAILY' | 'MONTHLY';

export interface AIAnalysis {
  id: string;
  analysisType: AIAnalysisType;
  referenceDate: string; // YYYY-MM-DD ou YYYY-MM
  referencePeriod: string; // ex: "24/09/2026" ou "Setembro/2026"
  inputHash: string;
  analysisText: string;
  model: string;
  createdAt: string;
  updatedAt: string;
}

export interface AppSettings {
  storeName: string;
  systemName: string;
  timezone: string;
  allowAttendantViewIndividualPerformance: boolean;
}

export interface DashboardMetrics {
  // Diário
  todayTotal: number;
  todayGoal: number;
  todayPercentage: number;
  todayDifference: number; // realizada - meta
  activeAttendantsCount: number;
  attendantsWithSupportCount: number;
  todayAveragePerAttendant: number;
  
  // Mensal
  monthTotal: number;
  monthGoal: number;
  monthPercentage: number;
  monthRemainingValue: number;
  monthDailyAverage: number;
  monthProjection: number;
  monthRemainingDays: number;
  monthRequiredPace: number;
  
  // Períodos e datas
  referenceDate: string;
  referenceMonth: string;
}

export interface AttendantPerformance {
  attendantId: string;
  attendantName: string;
  attendantCode: string;
  todayQuantity: number;
  monthQuantity: number;
  active: boolean;
  percentageOfMonth: number;
}
