import { z } from 'zod';

export const supportSchema = z.object({
  date: z.string().regex(/^\d{4}-\d{2}-\d{2}$/, { message: 'Data inválida. Use o formato AAAA-MM-DD.' }),
  attendantId: z.string().min(1, { message: 'Selecione um atendente.' }),
  quantity: z
    .number({ invalid_type_error: 'A quantidade deve ser um número inteiro.' })
    .int({ message: 'A quantidade não pode conter casas decimais.' })
    .min(1, { message: 'A quantidade mínima permitida é 1.' }),
  observation: z.string().max(500, { message: 'A observação não pode exceder 500 caracteres.' }).optional(),
});

export const attendantSchema = z.object({
  name: z.string().min(2, { message: 'O nome do atendente deve ter pelo menos 2 caracteres.' }).max(100),
  code: z.string().min(1, { message: 'O código identificador é obrigatório.' }).max(20),
  active: z.boolean().default(true),
});

export const userSchema = z.object({
  name: z.string().min(2, { message: 'O nome deve ter no mínimo 2 caracteres.' }),
  email: z.string().email({ message: 'E-mail inválido.' }),
  role: z.enum(['ADMIN', 'ATENDENTE'], { message: 'Selecione um perfil válido.' }),
  active: z.boolean().default(true),
  attendantId: z.string().optional(),
});

export const goalSchema = z.object({
  type: z.enum(['DAILY_STORE', 'MONTHLY_STORE', 'DAILY_ATTENDANT', 'MONTHLY_ATTENDANT']),
  attendantId: z.string().optional(),
  targetValue: z
    .number({ invalid_type_error: 'A meta deve ser um número válido.' })
    .int({ message: 'A meta deve ser um número inteiro.' })
    .min(1, { message: 'A meta deve ser no mínimo 1.' }),
  startDate: z.string().regex(/^\d{4}-\d{2}-\d{2}$/, { message: 'Data inicial inválida.' }),
  endDate: z.string().regex(/^\d{4}-\d{2}-\d{2}$/, { message: 'Data final inválida.' }).nullable().optional(),
  active: z.boolean().default(true),
});

export const aiSettingsSchema = z.object({
  provider: z.literal('Google Gemini'),
  model: z.string().min(1, { message: 'Selecione um modelo válido.' }),
  enabled: z.boolean(),
  dailyAnalysisEnabled: z.boolean(),
  monthlyAnalysisEnabled: z.boolean(),
  autoGenerateDaily: z.boolean(),
  autoGenerateMonthly: z.boolean(),
});

export const apiKeyInputSchema = z.object({
  apiKey: z.string().min(10, { message: 'A API Key do Google Gemini deve ser válida.' }),
});
