import { LocalDatabase } from '../storage/localDatabase';
import { AISettings, AppSettings, UserProfile } from '../../types';
import { aiSettingsSchema } from '../../validators/schemas';
import { AuditService } from '../audit/auditService';

export class SettingsService {
  static getAISettings(): AISettings {
    return LocalDatabase.getAISettings();
  }

  static updateAISettings(currentUser: UserProfile, data: Partial<AISettings>): AISettings {
    if (currentUser.role !== 'ADMIN') {
      throw new Error('Acesso negado: Somente administradores podem alterar configurações.');
    }

    const current = LocalDatabase.getAISettings();
    const updated: AISettings = {
      ...current,
      ...data,
      updatedAt: new Date().toISOString(),
      updatedBy: currentUser.name,
    };

    aiSettingsSchema.parse({
      provider: updated.provider,
      model: updated.model,
      enabled: updated.enabled,
      dailyAnalysisEnabled: updated.dailyAnalysisEnabled,
      monthlyAnalysisEnabled: updated.monthlyAnalysisEnabled,
      autoGenerateDaily: updated.autoGenerateDaily,
      autoGenerateMonthly: updated.autoGenerateMonthly,
    });

    LocalDatabase.saveAISettings(updated);

    AuditService.logSystemAction(
      currentUser.id,
      currentUser.name,
      currentUser.role,
      'AI_CONFIG_UPDATED',
      'AI_SETTINGS',
      updated.id,
      { model: updated.model, enabled: updated.enabled }
    );

    return updated;
  }

  /**
   * Salva a API Key no AWS Secrets Manager (persistência segura)
   * NUNCA retorna o valor da chave.
   */
  static async saveGeminiApiKey(currentUser: UserProfile, _apiKey: string): Promise<{ success: boolean; message: string }> {
    if (currentUser.role !== 'ADMIN') {
      throw new Error('Acesso negado: Somente administradores podem configurar credenciais.');
    }

    if (!_apiKey || _apiKey.trim().length < 10) {
      throw new Error('A API Key fornecida é inválida.');
    }

    // Simula o PutSecretValue no AWS Secrets Manager via Lambda backend
    await new Promise((r) => setTimeout(r, 500));

    const settings = LocalDatabase.getAISettings();
    settings.isKeyConfigured = true;
    settings.updatedAt = new Date().toISOString();
    settings.updatedBy = currentUser.name;
    LocalDatabase.saveAISettings(settings);

    AuditService.logSystemAction(
      currentUser.id,
      currentUser.name,
      currentUser.role,
      'AI_API_KEY_UPDATED',
      'AWS_SECRETS_MANAGER',
      'apoio-tratamento/gemini',
      { status: 'SECRET_STORED_SECURELY' }
    );

    return {
      success: true,
      message: 'API Key persistida com sucesso no AWS Secrets Manager.',
    };
  }

  /**
   * Remove a API Key do AWS Secrets Manager
   */
  static async removeGeminiApiKey(currentUser: UserProfile): Promise<{ success: boolean; message: string }> {
    if (currentUser.role !== 'ADMIN') {
      throw new Error('Acesso negado: Somente administradores podem remover credenciais.');
    }

    await new Promise((r) => setTimeout(r, 400));

    const settings = LocalDatabase.getAISettings();
    settings.isKeyConfigured = false;
    settings.updatedAt = new Date().toISOString();
    settings.updatedBy = currentUser.name;
    LocalDatabase.saveAISettings(settings);

    AuditService.logSystemAction(
      currentUser.id,
      currentUser.name,
      currentUser.role,
      'AI_API_KEY_REMOVED',
      'AWS_SECRETS_MANAGER',
      'apoio-tratamento/gemini',
      { status: 'SECRET_REMOVED' }
    );

    return {
      success: true,
      message: 'API Key removida do AWS Secrets Manager. As análises de IA foram desabilitadas.',
    };
  }

  static getAppSettings(): AppSettings {
    return LocalDatabase.getAppSettings();
  }

  static updateAppSettings(currentUser: UserProfile, data: Partial<AppSettings>): AppSettings {
    if (currentUser.role !== 'ADMIN') {
      throw new Error('Acesso negado: Somente administradores podem alterar configurações gerais.');
    }

    const current = LocalDatabase.getAppSettings();
    const updated = { ...current, ...data };
    LocalDatabase.saveAppSettings(updated);

    AuditService.logSystemAction(
      currentUser.id,
      currentUser.name,
      currentUser.role,
      'AI_CONFIG_UPDATED',
      'APP_SETTINGS',
      undefined,
      { updatedFields: Object.keys(data) }
    );

    return updated;
  }
}
