import {
  UserProfile,
  Attendant,
  TreatmentSupport,
  TreatmentSupportAudit,
  AuditLog,
  Goal,
  AISettings,
  AIAnalysis,
  AppSettings,
} from '../../types';
import { APP_CONFIG } from '../../config';

// In-memory store fallback para ambientes de teste e Node
const memoryStore = new Map<string, string>();

const DEFAULT_AI_SETTINGS: AISettings = {
  id: 'ai-config-default',
  provider: 'Google Gemini',
  model: APP_CONFIG.defaultGeminiModel,
  enabled: true,
  isKeyConfigured: false, // Inicia não configurada em produção até que o ADMIN insira no Secrets Manager
  dailyAnalysisEnabled: true,
  monthlyAnalysisEnabled: true,
  autoGenerateDaily: false,
  autoGenerateMonthly: false,
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  updatedBy: 'Sistema',
};

const DEFAULT_APP_SETTINGS: AppSettings = {
  storeName: APP_CONFIG.storeName,
  systemName: APP_CONFIG.systemName,
  timezone: APP_CONFIG.timezone,
  allowAttendantViewIndividualPerformance: true,
};

export class LocalDatabase {
  private static get<T>(key: string, defaultValue: T): T {
    try {
      let item: string | null = null;
      if (typeof localStorage !== 'undefined') {
        item = localStorage.getItem(key);
      } else {
        item = memoryStore.get(key) || null;
      }

      if (item === null) {
        LocalDatabase.set(key, defaultValue);
        return defaultValue;
      }
      return JSON.parse(item) as T;
    } catch {
      return defaultValue;
    }
  }

  private static set<T>(key: string, value: T): void {
    try {
      const serialized = JSON.stringify(value);
      if (typeof localStorage !== 'undefined') {
        localStorage.setItem(key, serialized);
      } else {
        memoryStore.set(key, serialized);
      }
    } catch (e) {
      console.error(`Erro ao persistir chave ${key}:`, e);
    }
  }

  // User Profiles (Zerado para produção)
  static getUserProfiles(): UserProfile[] {
    return this.get<UserProfile[]>(APP_CONFIG.storageKeys.userProfiles, []);
  }

  static saveUserProfiles(users: UserProfile[]): void {
    this.set(APP_CONFIG.storageKeys.userProfiles, users);
  }

  // Attendants (Zerado para produção)
  static getAttendants(): Attendant[] {
    return this.get<Attendant[]>(APP_CONFIG.storageKeys.attendants, []);
  }

  static saveAttendants(attendants: Attendant[]): void {
    this.set(APP_CONFIG.storageKeys.attendants, attendants);
  }

  // Treatment Supports (Zerado para produção)
  static getSupports(): TreatmentSupport[] {
    return this.get<TreatmentSupport[]>(APP_CONFIG.storageKeys.supports, []);
  }

  static saveSupports(supports: TreatmentSupport[]): void {
    this.set(APP_CONFIG.storageKeys.supports, supports);
  }

  // Support Audits (Zerado para produção)
  static getSupportAudits(): TreatmentSupportAudit[] {
    return this.get<TreatmentSupportAudit[]>(APP_CONFIG.storageKeys.supportAudits, []);
  }

  static saveSupportAudits(audits: TreatmentSupportAudit[]): void {
    this.set(APP_CONFIG.storageKeys.supportAudits, audits);
  }

  // System Audit Logs (Zerado para produção)
  static getAuditLogs(): AuditLog[] {
    return this.get<AuditLog[]>(APP_CONFIG.storageKeys.auditLogs, []);
  }

  static saveAuditLogs(logs: AuditLog[]): void {
    this.set(APP_CONFIG.storageKeys.auditLogs, logs);
  }

  // Goals (Zerado para produção)
  static getGoals(): Goal[] {
    return this.get<Goal[]>(APP_CONFIG.storageKeys.goals, []);
  }

  static saveGoals(goals: Goal[]): void {
    this.set(APP_CONFIG.storageKeys.goals, goals);
  }

  // AI Settings (Configuração padrão limpa sem chave)
  static getAISettings(): AISettings {
    return this.get<AISettings>(APP_CONFIG.storageKeys.aiSettings, DEFAULT_AI_SETTINGS);
  }

  static saveAISettings(settings: AISettings): void {
    this.set(APP_CONFIG.storageKeys.aiSettings, settings);
  }

  // AI Analyses (Zerado)
  static getAIAnalyses(): AIAnalysis[] {
    return this.get<AIAnalysis[]>(APP_CONFIG.storageKeys.aiAnalyses, []);
  }

  static saveAIAnalyses(analyses: AIAnalysis[]): void {
    this.set(APP_CONFIG.storageKeys.aiAnalyses, analyses);
  }

  // App Settings
  static getAppSettings(): AppSettings {
    return this.get<AppSettings>(APP_CONFIG.storageKeys.appSettings, DEFAULT_APP_SETTINGS);
  }

  static saveAppSettings(settings: AppSettings): void {
    this.set(APP_CONFIG.storageKeys.appSettings, settings);
  }

  // Função para limpar todos os dados de armazenamento (Reset completo)
  static resetAllData(): void {
    if (typeof localStorage !== 'undefined') {
      Object.values(APP_CONFIG.storageKeys).forEach((k) => localStorage.removeItem(k));
    }
    memoryStore.clear();
  }
}
